# -------- 服务配置 -------
server:
  port: 8080
# ------  spring 配置 -----
spring:
  aop:
    proxy-target-class: true
  # 数据源 配置
  r2dbc:
#    url: r2dbc:h2:file:///${MODULE_DIR}/db/default
    url: r2dbc:mysql://etms.lemone.xyz:8306/qtms
    username: qtms
    password: qtms
  initialization-mode: always
  sql-script-encoding: UTF-8
  schema: 'classpath*:init/schema.sql'
  data : 'classpath*:init/data.sql'

  # 模板引擎配置
  thymeleaf:
    cache: false
