# -------- 服务配置 -------
server:
  port: 8080
# ------  spring 配置 -----
spring:
  aop:
    proxy-target-class: true
# 数据源 配置
  datasource:
    druid:
      url: jdbc:h2:${MODULE_DIR}/db/default;create=true
      username: lemon
      password: Biyu5YzU+6sxDRbmWEa3B2uUcImzDo0BuXjTlL505+/pTb+/0Oqd3ou1R6J8+9Fy3CYrM18nBDqf6wAaPgUGOg==
      validation-query: select 1
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: druid
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions:
        profile-enable: true
      filter:
        config:
          enabled: true
      filters: config
      connection-properties: config.decrypt=true

  # 模板引擎配置
  thymeleaf:
   cache: false

#  shiro 配置
shiro:
  loginUrl: /login/*
  successUrl: /
  unauthorizedUrl: /login.html


