# -------- 服务配置 -------
server:
  port: 8080
# ------  spring 配置 -----
spring:
# 数据源 配置
  datasource:
    druid:
      url: jdbc:mysql://bdm274886632.my3w.com:3306/bdm274886632_db
      username: bdm274886632
      password: jJ3ERn07a5e9E+7pkYx3cral7HsoDvbruUVf82LAYz9CWO+IRuTnqOSj/I0s0q1DeRwHLHzCGo8x26KA7nqDyQ==
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow: server.mint123.xyz
        login-username: druid
        login-password: druid
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions:
        profile-enable: true
      filter:
        config:
          enabled: true
      filters: config
      connection-properties: config.decrypt=true

  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
# spring session 配置
  session:
    redis:
      namespace: lemon_session
#------ mybatis 配置 ----------
mybatis:
  type-aliases-package: xyz.mint123.lemon
